### ISSUE TITLE
use of pi as a name can interfere with other code that uses the default use of "pi" for calculations

### ISSUE THREAD

**Issue by bcohen27** [ebird/ebird-best-practices#4]
The use of **pi** as a name can interfere with other bird-related code that uses the default use of "pi" for calculations. Specifically, when using R to analyze Motus data, pi is used to calculate radians for measuring distances between lat/lon coordinates in the site_transit function.

**Comment by mstrimas** [comment]
good catch, thanks! also, hilarious that R allows you to overwrite `pi`. anyway, it should be fixed now.
