### ISSUE TITLE
Packages no longer available

### ISSUE THREAD

**Issue by maclopes** [ebird/ebird-best-practices#6]
Thanks for the paper and the code sharing.
I am trying to run the repo but I get blocked when installing a couple of packages. Is there an update with more recent packages?

**Comment by mstrimas** [comment]
When I run `remotes::install_github("ebird/ebird-best-practices")` to install packages for the Best Practices guide, I don't run in to any errors. Can you post a list of the packages that are causing you trouble?

**Comment by maclopes** [comment]
it works, thanks.
