### ISSUE TITLE
Data was removed

### ISSUE THREAD

**Issue by RichardLitt** [ebird/ebird-best-practices#9]
From this section: 

> Since the EBD is updated monthly, you will likely recieve a different version of the data than the October 2023 version used throughout the rest of this lesson. Provided you update the filenames of the downloaded files accordingly, the difference in versions will not be an issue. However, if you want to download and use exactly the same files used in this lesson, you can [download the corresponding EBD zip file](https://cornell.box.com/shared/static/lwd1rm163r2pfe389fi0n084hmyr0jbv.zip).

This link no longer works.

**Comment by mstrimas** [comment]
Uh oh, looks like I managed to delete this file while trying to free up space on Box. Took my a while to track down the original files, but I've re-uploaded them here

https://cornell.box.com/shared/static/kp930twpdd6bewrs315a39y9zn7mwsv2.zip


I'm updating the website now to fix the link there as well. Let me know if this file still isn't downloading properly. Thanks!

**Comment by RichardLitt** [comment]
Seems to work now. Thanks!
